name: SimplePointPlugin
version: 2.0.0
main: net.azisaba.simplepoint.SimplePointPlugin
api-version: 1.16
author: pino223
commands:
  spp:
    description: SimplePointPlugin Admin Command
    permission: spp.admin
  spt:
    description: SimplePointPlugin Player Command
  sppt:
    description: チーム用コマンド
    permission: sppt.admin
  myp:
    description: Check your points quickly
    usage: /myp <id>
  ranking:
    description: Check the ranking quickly
    usage: /ranking <id>
  teaminfo:
    description: Check your points quickly
    usage: /teaminfo <group> <team>