name: SimplePointPlugin
version: 1.2.1
main: net.azisaba.simplepoint.SimplePointPlugin
api-version: 1.16
author: pino223
commands:
  spp:
    description: SimplePointPlugin Admin Command
    permission: spp.admin
  spt:
    description: SimplePointPlugin Player Command
  sptt:
    description: チーム用コマンド
    permission: sptt.admin
  myp:
    description: Check your points quickly
    usage: /myp <id>
  ranking:
    description: Check the ranking quickly
    usage: /ranking <id>